# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: B E A R 4 5 4
email: james@bear454.com
description: > # this means to ignore newlines until "baseurl:"
  2 parts tech, 1 part sarcasm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bear454.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bear454
github_username:  bear454

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  # Minima date format
  # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%Y-%m-%d"

google_analytics: UA-106278876-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
